### ISSUE TITLE
config.json issue

### ISSUE THREAD

**Issue by doom699** [Crimeraaa-S1GMA/ScratchCommentBot#1]
hello so uhh this happened

    config = open("config.json", "r")

FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

idk how to fix it. please tell me.

**Comment by Crimeraaa-S1GMA** [comment]
Do you have a config.json file in the exact same directory as the main.py file?

**Comment by doom699** [comment]
yes

**Comment by Crimeraaa-S1GMA** [comment]
Check the name, and make sure to enable viewing file extensions in the explorer

Clearly the open function doesn't seem to find a config file for a reason

**Comment by doom699** [comment]
the name is "config.json"

**Comment by Crimeraaa-S1GMA** [comment]
Also make sure it's in the same folder. If not, I cannot see what the problem would be so I cannot help you

**Comment by doom699** [comment]
it is

**Comment by Crimeraaa-S1GMA** [comment]
Then I can't see what the problem would be, I'm closing as can't repro
